"use strict";
const APP_MESSAGES = {
    SUCCESS: "Successfully.",
    RUNDOWN_ERROR: "Rundown api error.",
    UNAUTHORIZED: "Unauthorized",
    FORBIDDEN: "Forbidden",
    SUCCESSFULLY_REGISTERD: "Successfully registered.",
    SUCCESSFULLY_SEND_RESET_LINK: "Successfully send reset link in your email Id.",
    SUCCESSFULLY_UPDATED_PASSWORD: "Password has been successfully updated.",
    PROFILE_SUCCESSFULLY_UPDATED: "Profile has been successfully updated.",
    DATABASE_ERROR: "Database error.",
    EMAIL_ALREDAY_VERIFIED: "Email already verified.",
    PLEASE_TRY_AGAIN: "Please try again.",
    EMAIL_ALREDAY_EXIT: "Email already exists.",
    USERNAME_ALREDAY_EXIT: "Username already exists.",
    SECRET_KEY_ALREDAY_EXIT: "Secret key already exists.",
    INVALID_CONTENT_LANGUAGE: "Invalid content language",
    IMPLEMENTATION_ERROR: "Implementation error.",
    DUPLICATE_IS_NOT_ALLOWED: "Duplicate values not allowed on index.",
    INVALID_OBJECT_ID_FROMATE: "Invalid object formate.",
    INVALID_IMAGE_FORMAT: "Invalid image format.",
    INVALID_EMAIL_PASSWORD: "Invalid email or password.",
    INVALID_PASSWORD: "Wrong password",
    EMAIL_OR_USERNAME_REQUIRED: "Email or username required.",
    RESET_LINK_EXPIRED: "Reset link has been expired.",
    RESET_TOKEN_EXPIRED: "Reset token has been expired.",
    INVALID_EMAIL_ID: "Invalid email Id.",
    EMAIL_ID_DOES_NOT_EXISTS: "Email Id does not exists.",
    INVALID_USERNAME_PASSWORD: "Invalid username or password.",
    INVALID_USERNAME: "Invalid username.",
    INVALID_ADMIN_ID: "Invalid admin id.",
    INVALID_INPUT_PARAMETER: "Invalid input parameter.",
    INVALID_TOKEN: "Invalid token provided.",
    IMP_ERROR: "Implementation error.",
    TOKEN_ALREADY_EXPIRED: "Token already expired.",
    TOKEN_NOT_GENRATED_CORRECTLY: "Token not genrated correctly,please try again.",
    ADMIN_BLOCKED: "Admin is blocked.",
    ADMIN_NOT_FOUND: "Admin not found.",
    SAME_PASSWORD_NOT_ALLOWED: "Previous password are not allowed.",
    OLD_PASSWORD_NOT_MATCH: "Old password is wrong.",
    PASSWORD_RESET_LINK_SEND_YOUR_EMAIL: "Resent link was sent on your register email id.",
    INVALID_PASSWORD_RESET_TOKEN: "Invalid password reset token.",
    PASSWORD_CHANGED_SUCCESSFULLY: "Password changed sucessfully.",
    INVALID_OTP: "Invalid otp code.",
    OTP_CODE_SEND_YOUR_REGISTER_PHONE_NUMBER: "Otp code send your register phone number.",
    PHONE_NUMBER_ALREADY_EXISTS: "Phone number already exists.",
    LATEST_VERSION_LESS_THEN_CRITICAL_VERSION: "Latest version should be less than or equal to critical version.",
    USER_NAME_ALREADY_EXISTS: "Username already exists.",
    INVALID_USERNAME_EMAIL: "Invalid email/username.",
    USER_NOT_FOUND: "User does not exists.",
    USER_BLOCKED: "User block successfully.",
    USER_UN_BLOCKED: "User un-block successfully.",
    USER_DELETED: "User deleted successfully.",
    USER_ACTIVE: "User is actived.",
    USER_UN_ACTIVE: "User is actived.",
    USER_REGISTER_SUCCESSFULLY: "User registered successfully.",
    USER_LOGIN_SUCCESSFULLY: "User logged in successfully.",
    USER_LOGOUT_SUCCESSFULLY: "User logged out successfully.",
    USER_PROFILE_UPDATED_SUCCESSFULLY: "User profile updated successfully.",
    USER_BANCKROLL_UPDATED_SUCCESSFULLY: "User updated successfully.",
    USER_CHANGED_PASSWORD_SUCCESSFULLY: "User change password successfully.",
    USER_DELETED_ACCOUNT_SUCCESSFULLY: "User deleted account successfully.",
    FILE_UPLOADED_SUCCESSFULLY: "File successfully.",
    OTP_VERIFIED: "Otp code verified.",
    USER_CLEAR_NOTIFICATION: "User clear notification.",
    USER_CLEAR_ALL_NOTIFICATION: "User clear all notification.",
    USER_ADD_ALGORITHEM_SUCCESSFULLY: "User add algorithm successfully.",
    USER_ADD_SUCCESSFULLY: "User add successfully.",
    USER_DELETED_ACCOUNT_SUCCESSFULLY: "User account deleted successfully.",
    ADMIN_REGISTER_SUCCESSFULLY: "Admin register successfully.",
    ADMIN_LOGIN_SUCCESSFULLY: "Admin login successfully.",
    ADMIN_LOGOUT_SUCCESSFULLY: "Admin logout successfully.",
    ADMIN_PROFILE_UPDATED_SUCCESSFULLY: "Admin update profile successfully.",
    ADMIN_CHANGED_PASSWORD_SUCCESSFULLY: "Admin changed password successfully.",
    ADMIN_DELETED_ACCOUNT_SUCCESSFULLY: "Admin deleted account successfully.",
    FILE_UPLOADED_SUCCESSFULLY: "File upload successfully.",
    ADMIN_CLEAR_NOTIFICATION: "Admin clear notification successfully.",
    ADMIN_CLEAR_ALL_NOTIFICATION: "Admin clear all notification successfully.",
    ADMIN_ADD_ALGORITHEM_SUCCESSFULLY: "Admin add algorithm successfully.",
    ADMIN_UPDATE_ALGORITHEM_SUCCESSFULLY: "Admin update algorithm successfully.",
    ADMIN_DELETED_ALGORITHEM_SUCCESSFULLY: "Admin deleted algorithm successfully.",
    APP_VERSION_ADDSUCCESFULLY: "Admin set app version sucessfully.",
    DATA_NOT_FOUND: "Data not found.",
    NOTIFICATION_SEND_TO_USER: "Notification send to user successfully.",
    CREDENTIALS_ADDED_SUCESSFULLY: 'Credentials added successfully.',
    CREDENTIALS_ACTIVE_SUCESSFULLY: 'Credentials active successfully.',
    CREDENTIALS_UN_ACTIVE_SUCESSFULLY: 'Credentials un-active successfully.',
    CREDENTIALS_NOT_FOUND: 'Credentials not found successfully.',
    OTHER_CREDENTIALS_ACTIVE: 'Other credentials is active.',
    CURRENT_CREDENTIALS_ALREADY_ACTIVE: 'Current credentials is already active.',
    ADMIN_NOT_FOUND: "Admin does not exists.",
    ADMIN_BLOCKED: "Admin block successfully.",
    ADMIN_UN_BLOCKED: "Admin un-block successfully.",
    ADMIN_DELETED: "Admin deleted successfully.",
    ADMIN_ACTIVE: "Admin is actived.",
    ADMIN_UN_ACTIVE: "Admin is actived.",
    ADMIN_LOGIN: "Admin Login sucessfully",
    INVALID_BORROWER_ID : "Invaid Borrower Id",
    LOAN_ADD_SUCCESSFULLY:"Loan added sucessfully",
    INVALID_LOAN_ID : "Invalid loan Id",
    SUCCESSFULLY_UPDATED : "Updated sucessfully",
    FETCHED_SUCCESSFULLY : "Fetched Sucessfully",
    SUCCESSFULLY_DELETED : "Deleted Sucessfully"
};
module.exports = {
    APP_MESSAGES: APP_MESSAGES
};