module.exports = {
    User: require('./User'),
    Otp: require('./Otp'),
    Admin: require('./Admin'),
    SuperAdmin: require('./SuperAdmin'),
    Address: require('./Address'),
    UserDevice: require('./UserDevice'),
    DriverDevice: require('./DriverDevice'),
    AppLayout: require('./AppLayout'),
    AppSetting: require('./AppSetting'),
    DefaultAppLayout: require('./DefaultAppLayout'),
    UserNotification : require('./UserNotification'),
    AdminNotification : require('./AdminNotification'),
    SuperAdminNotification : require('./SuperAdminNotification'),
    AppVersion:require('./AppVersion'),
    ContactUs:require('./ContactUs'),
    DefaultEmailMessages : require('./DefaultEmailMessages'),
    DefaultPushMessages : require('./DefaultPushMessages'),
    DefaultSmsMessages : require('./DefaultSmsMessages'),
    EmailMessages : require('./EmailMessages'),
    PushMessages : require('./PushMessages'),
    SmsMessages : require('./SmsMessages'),
    Credentials : require('./Credentials'),
    Borrower : require('./Borrower'),
    Loan : require('./loan'),
    Expenses : require('./Expenses')
};
